CREATE TABLE category (_id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, url TEXT, page INTEGER);

INSERT INTO category VALUES (NULL,'Action','http://manga24h.com/Action.html/',58);
INSERT INTO category VALUES (NULL,'Adult','http://manga24h.com/Adult.html/',4);
INSERT INTO category VALUES (NULL,'Adventure','http://manga24h.com/Adventure.html/',27);
INSERT INTO category VALUES (NULL,'Anime','http://manga24h.com/Anime.html/',2);
INSERT INTO category VALUES (NULL,'Baseball','http://manga24h.com/Baseball.html/',1);
INSERT INTO category VALUES (NULL,'Comedy','http://manga24h.com/Comedy.html/',72);
INSERT INTO category VALUES (NULL,'Comic','http://manga24h.com/Comic.html/',2);
INSERT INTO category VALUES (NULL,'Cooking','http://manga24h.com/Cooking.html/',1);
INSERT INTO category VALUES (NULL,'Detective','http://manga24h.com/Detective.html/',1);
INSERT INTO category VALUES (NULL,'Doujinshi','http://manga24h.com/Doujinshi.html/',2);
INSERT INTO category VALUES (NULL,'Drama','http://manga24h.com/Drama.html/',36);
INSERT INTO category VALUES (NULL,'Ecchi','http://manga24h.com/Ecchi.html/',27);
INSERT INTO category VALUES (NULL,'Fantasy','http://manga24h.com/Fantasy.html/',35);
INSERT INTO category VALUES (NULL,'Football','http://manga24h.com/Football.html/',1);
INSERT INTO category VALUES (NULL,'Futanari','http://manga24h.com/Futanari.html/',1);
INSERT INTO category VALUES (NULL,'Game','http://manga24h.com/Game.html/',1);
INSERT INTO category VALUES (NULL,'Gender Bender','http://manga24h.com/Gender-Bender.html/',6);
INSERT INTO category VALUES (NULL,'Gothic','http://manga24h.com/Gothic.html/',1);
INSERT INTO category VALUES (NULL,'Harem','http://manga24h.com/Harem.html/',14);
INSERT INTO category VALUES (NULL,'Historical','http://manga24h.com/Historical.html/',11);
INSERT INTO category VALUES (NULL,'Horror','http://manga24h.com/Horror.html/',11);
INSERT INTO category VALUES (NULL,'Huyền Huyễn','http://manga24h.com/Huyen-Huyen.html/',1);
INSERT INTO category VALUES (NULL,'Josei','http://manga24h.com/Josei.html/',3);
INSERT INTO category VALUES (NULL,'Live Action','http://manga24h.com/Live-Action.html/',1);
INSERT INTO category VALUES (NULL,'Lolicon','http://manga24h.com/Lolicon.html/',1);
INSERT INTO category VALUES (NULL,'Magic','http://manga24h.com/Magic.html/',1);
INSERT INTO category VALUES (NULL,'Manhua','http://manga24h.com/Manhua.html/',15);
INSERT INTO category VALUES (NULL,'Manhwa','http://manga24h.com/Manhwa.html/',6);
INSERT INTO category VALUES (NULL,'Martial Arts','http://manga24h.com/Martial-Arts.html/',13);
INSERT INTO category VALUES (NULL,'Mature','http://manga24h.com/Mature.html/',10);
INSERT INTO category VALUES (NULL,'Mecha','http://manga24h.com/Mecha.html/',2);
INSERT INTO category VALUES (NULL,'Music','http://manga24h.com/Music.html/',1);
INSERT INTO category VALUES (NULL,'Mystery','http://manga24h.com/Mystery.html/',14);
INSERT INTO category VALUES (NULL,'Novel','http://manga24h.com/Novel.html/',1);
INSERT INTO category VALUES (NULL,'One Shot','http://manga24h.com/Oneshot.html/',7);
INSERT INTO category VALUES (NULL,'Psychological','http://manga24h.com/Psychological.html/',10);
INSERT INTO category VALUES (NULL,'Romance','http://manga24h.com/Romance.html/',63);
INSERT INTO category VALUES (NULL,'School Life','http://manga24h.com/School-Life.html/',43);
INSERT INTO category VALUES (NULL,'Sci-fi','http://manga24h.com/Sci-fi.html/',12);
INSERT INTO category VALUES (NULL,'Seinen','http://manga24h.com/Seinen.html/',27);
INSERT INTO category VALUES (NULL,'Shoujo','http://manga24h.com/Shoujo.html/',29);
INSERT INTO category VALUES (NULL,'Shoujo Ai','http://manga24h.com/Shoujo-Ai.html/',2);
INSERT INTO category VALUES (NULL,'Shounen','http://manga24h.com/Shounen.html/',51);
INSERT INTO category VALUES (NULL,'Shounen Ai','http://manga24h.com/Shounen-Ai.html/',3);
INSERT INTO category VALUES (NULL,'Slice Of Life','http://manga24h.com/Slice-Of-Life.html/',17);
INSERT INTO category VALUES (NULL,'Smut','http://manga24h.com/Smut.html/',2);
INSERT INTO category VALUES (NULL,'Soft Yaoi','http://manga24h.com/Soft-Yaoi.html/',1);
INSERT INTO category VALUES (NULL,'Soft Yuri','http://manga24h.com/Soft-Yuri.html/',1);
INSERT INTO category VALUES (NULL,'Sports','http://manga24h.com/Sports.html/',6);
INSERT INTO category VALUES (NULL,'Super Power','http://manga24h.com/Super-Power.html/',1);
INSERT INTO category VALUES (NULL,'Supernatural','http://manga24h.com/Supernatural.html/',35);
INSERT INTO category VALUES (NULL,'Thriller','http://manga24h.com/Thriller.html/',1);
INSERT INTO category VALUES (NULL,'Tragedy','http://manga24h.com/Tragedy.html/',10);
INSERT INTO category VALUES (NULL,'Truyện Scan','http://manga24h.com/Truyen-Scan.html/',1);
INSERT INTO category VALUES (NULL,'Truyện Việt Nam','http://manga24h.com/Truyen-Viet-Nam.html/',1);
INSERT INTO category VALUES (NULL,'Vampires','http://manga24h.com/Vampires.html/',1);
INSERT INTO category VALUES (NULL,'Violence','http://manga24h.com/Violence.html/',1);
INSERT INTO category VALUES (NULL,'VN Comic','http://manga24h.com/VN-Comic.html/',1);